// ...existing code...
export const elementsData = [
  { atomicNumber: 1,  symbol: 'H',  name: 'Hydrogen',      nameZh: '氢',      period: 1, group: 1,  atomicMass: 1.008,    types: ['nonmetal'] },
  { atomicNumber: 2,  symbol: 'He', name: 'Helium',        nameZh: '氦',      period: 1, group: 18, atomicMass: 4.0026,  types: ['noble-gas','nonmetal'] },

  { atomicNumber: 3,  symbol: 'Li', name: 'Lithium',       nameZh: '锂',      period: 2, group: 1,  atomicMass: 6.94,    types: ['alkali-metal','metal'] },
  { atomicNumber: 4,  symbol: 'Be', name: 'Beryllium',     nameZh: '铍',      period: 2, group: 2,  atomicMass: 9.0122,  types: ['alkaline-earth','metal'] },
  { atomicNumber: 5,  symbol: 'B',  name: 'Boron',         nameZh: '硼',      period: 2, group: 13, atomicMass: 10.81,   types: ['metalloid'] },
  { atomicNumber: 6,  symbol: 'C',  name: 'Carbon',        nameZh: '碳',      period: 2, group: 14, atomicMass: 12.011,  types: ['nonmetal'] },
  { atomicNumber: 7,  symbol: 'N',  name: 'Nitrogen',      nameZh: '氮',      period: 2, group: 15, atomicMass: 14.007,  types: ['nonmetal'] },
  { atomicNumber: 8,  symbol: 'O',  name: 'Oxygen',        nameZh: '氧',      period: 2, group: 16, atomicMass: 15.999,  types: ['nonmetal'] },
  { atomicNumber: 9,  symbol: 'F',  name: 'Fluorine',      nameZh: '氟',      period: 2, group: 17, atomicMass: 18.998,  types: ['halogen','nonmetal'] },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon',          nameZh: '氖',      period: 2, group: 18, atomicMass: 20.180,  types: ['noble-gas','nonmetal'] },

  { atomicNumber: 11, symbol: 'Na', name: 'Sodium',        nameZh: '钠',      period: 3, group: 1,  atomicMass: 22.990,  types: ['alkali-metal','metal'] },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium',     nameZh: '镁',      period: 3, group: 2,  atomicMass: 24.305,  types: ['alkaline-earth','metal'] },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminium',     nameZh: '铝',      period: 3, group: 13, atomicMass: 26.982,  types: ['post-transition','metal'] },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon',       nameZh: '硅',      period: 3, group: 14, atomicMass: 28.085,  types: ['metalloid'] },
  { atomicNumber: 15, symbol: 'P',  name: 'Phosphorus',    nameZh: '磷',      period: 3, group: 15, atomicMass: 30.974,  types: ['nonmetal'] },
  { atomicNumber: 16, symbol: 'S',  name: 'Sulfur',        nameZh: '硫',      period: 3, group: 16, atomicMass: 32.06,   types: ['nonmetal'] },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine',      nameZh: '氯',      period: 3, group: 17, atomicMass: 35.45,   types: ['halogen','nonmetal'] },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon',         nameZh: '氩',      period: 3, group: 18, atomicMass: 39.948,  types: ['noble-gas','nonmetal'] },

  { atomicNumber: 19, symbol: 'K',  name: 'Potassium',     nameZh: '钾',      period: 4, group: 1,  atomicMass: 39.098,  types: ['alkali-metal','metal'] },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium',       nameZh: '钙',      period: 4, group: 2,  atomicMass: 40.078,  types: ['alkaline-earth','metal'] },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium',      nameZh: '钪',      period: 4, group: 3,  atomicMass: 44.956,  types: ['transition','metal'] },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium',      nameZh: '钛',      period: 4, group: 4,  atomicMass: 47.867,  types: ['transition','metal'] },
  { atomicNumber: 23, symbol: 'V',  name: 'Vanadium',      nameZh: '钒',      period: 4, group: 5,  atomicMass: 50.942,  types: ['transition','metal'] },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium',      nameZh: '铬',      period: 4, group: 6,  atomicMass: 51.996,  types: ['transition','metal'] },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese',     nameZh: '锰',      period: 4, group: 7,  atomicMass: 54.938,  types: ['transition','metal'] },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron',          nameZh: '铁',      period: 4, group: 8,  atomicMass: 55.845,  types: ['transition','metal'] },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt',        nameZh: '钴',      period: 4, group: 9,  atomicMass: 58.933,  types: ['transition','metal'] },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel',        nameZh: '镍',      period: 4, group: 10, atomicMass: 58.693,  types: ['transition','metal'] },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper',        nameZh: '铜',      period: 4, group: 11, atomicMass: 63.546,  types: ['transition','metal'] },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc',          nameZh: '锌',      period: 4, group: 12, atomicMass: 65.38,   types: ['transition','metal'] },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium',       nameZh: '镓',      period: 4, group: 13, atomicMass: 69.723,  types: ['post-transition','metal'] },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium',     nameZh: '锗',      period: 4, group: 14, atomicMass: 72.630,  types: ['metalloid'] },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic',       nameZh: '砷',      period: 4, group: 15, atomicMass: 74.922,  types: ['metalloid'] },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium',      nameZh: '硒',      period: 4, group: 16, atomicMass: 78.971,  types: ['nonmetal'] },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine',       nameZh: '溴',      period: 4, group: 17, atomicMass: 79.904,  types: ['halogen','nonmetal'] },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton',       nameZh: '氪',      period: 4, group: 18, atomicMass: 83.798,  types: ['noble-gas','nonmetal'] },

  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium',      nameZh: '铷',      period: 5, group: 1,  atomicMass: 85.468,  types: ['alkali-metal','metal'] },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium',     nameZh: '锶',      period: 5, group: 2,  atomicMass: 87.62,   types: ['alkaline-earth','metal'] },
  { atomicNumber: 39, symbol: 'Y',  name: 'Yttrium',       nameZh: '钇',      period: 5, group: 3,  atomicMass: 88.906,  types: ['transition','metal'] },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium',     nameZh: '锆',      period: 5, group: 4,  atomicMass: 91.224,  types: ['transition','metal'] },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium',       nameZh: '铌',      period: 5, group: 5,  atomicMass: 92.906,  types: ['transition','metal'] },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum',    nameZh: '钼',      period: 5, group: 6,  atomicMass: 95.95,   types: ['transition','metal'] },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium',    nameZh: '锝',      period: 5, group: 7,  atomicMass: 98,      types: ['transition','metal','radioactive'] },
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium',     nameZh: '钌',      period: 5, group: 8,  atomicMass: 101.07,  types: ['transition','metal'] },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium',       nameZh: '铑',      period: 5, group: 9,  atomicMass: 102.91,  types: ['transition','metal'] },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium',     nameZh: '钯',      period: 5, group: 10, atomicMass: 106.42,  types: ['transition','metal'] },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver',        nameZh: '银',      period: 5, group: 11, atomicMass: 107.87,  types: ['transition','metal'] },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium',       nameZh: '镉',      period: 5, group: 12, atomicMass: 112.41,  types: ['transition','metal','radioactive'] },
  { atomicNumber: 49, symbol: 'In', name: 'Indium',        nameZh: '铟',      period: 5, group: 13, atomicMass: 114.82,  types: ['post-transition','metal'] },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin',           nameZh: '锡',      period: 5, group: 14, atomicMass: 118.71,  types: ['post-transition','metal'] },
  { atomicNumber: 51, symbol: 'Sb', name: 'Antimony',      nameZh: '锑',      period: 5, group: 15, atomicMass: 121.76,  types: ['metalloid'] },
  { atomicNumber: 52, symbol: 'Te', name: 'Tellurium',     nameZh: '碲',      period: 5, group: 16, atomicMass: 127.60,  types: ['metalloid'] },
  { atomicNumber: 53, symbol: 'I',  name: 'Iodine',        nameZh: '碘',      period: 5, group: 17, atomicMass: 126.90,  types: ['halogen','nonmetal','radioactive'] },
  { atomicNumber: 54, symbol: 'Xe', name: 'Xenon',         nameZh: '氙',      period: 5, group: 18, atomicMass: 131.29,  types: ['noble-gas','nonmetal'] },

  { atomicNumber: 55, symbol: 'Cs', name: 'Cesium',        nameZh: '铯',      period: 6, group: 1,  atomicMass: 132.91,  types: ['alkali-metal','metal','radioactive'] },
  { atomicNumber: 56, symbol: 'Ba', name: 'Barium',        nameZh: '钡',      period: 6, group: 2,  atomicMass: 137.33,  types: ['alkaline-earth','metal'] },

  // Lanthanides: La 放在主表 (group 3), 58-71 放在 f-block
  { atomicNumber: 57, symbol: 'La', name: 'Lanthanum',     nameZh: '镧',      period: 6, group: 3,  atomicMass: 138.905, types: ['lanthanide','metal'] },
  { atomicNumber: 58, symbol: 'Ce', name: 'Cerium',        nameZh: '铈',      period: 6, group: null, atomicMass: 140.116, types: ['lanthanide','metal'] },
  { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium',  nameZh: '镨',      period: 6, group: null, atomicMass: 140.908, types: ['lanthanide','metal'] },
  { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium',     nameZh: '钕',      period: 6, group: null, atomicMass: 144.242, types: ['lanthanide','metal'] },
  { atomicNumber: 61, symbol: 'Pm', name: 'Promethium',    nameZh: '钷',      period: 6, group: null, atomicMass: 145,      types: ['lanthanide','metal','radioactive'] },
  { atomicNumber: 62, symbol: 'Sm', name: 'Samarium',      nameZh: '钐',      period: 6, group: null, atomicMass: 150.36,  types: ['lanthanide','metal'] },
  { atomicNumber: 63, symbol: 'Eu', name: 'Europium',      nameZh: '铕',      period: 6, group: null, atomicMass: 151.964, types: ['lanthanide','metal'] },
  { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium',    nameZh: '钆',      period: 6, group: null, atomicMass: 157.25,  types: ['lanthanide','metal'] },
  { atomicNumber: 65, symbol: 'Tb', name: 'Terbium',       nameZh: '铽',      period: 6, group: null, atomicMass: 158.925, types: ['lanthanide','metal'] },
  { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium',    nameZh: '镝',      period: 6, group: null, atomicMass: 162.50,  types: ['lanthanide','metal'] },
  { atomicNumber: 67, symbol: 'Ho', name: 'Holmium',       nameZh: '钬',      period: 6, group: null, atomicMass: 164.930, types: ['lanthanide','metal'] },
  { atomicNumber: 68, symbol: 'Er', name: 'Erbium',        nameZh: '铒',      period: 6, group: null, atomicMass: 167.259, types: ['lanthanide','metal'] },
  { atomicNumber: 69, symbol: 'Tm', name: 'Thulium',       nameZh: '铥',      period: 6, group: null, atomicMass: 168.934, types: ['lanthanide','metal'] },
  { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium',     nameZh: '镱',      period: 6, group: null, atomicMass: 173.045, types: ['lanthanide','metal'] },
  { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium',      nameZh: '镥',      period: 6, group: null, atomicMass: 174.967, types: ['lanthanide','metal'] },

  { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium',       nameZh: '铪',      period: 6, group: 4,  atomicMass: 178.49,  types: ['transition','metal'] },
  { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum',      nameZh: '钽',      period: 6, group: 5,  atomicMass: 180.95,  types: ['transition','metal'] },
  { atomicNumber: 74, symbol: 'W',  name: 'Tungsten',      nameZh: '钨',      period: 6, group: 6,  atomicMass: 183.84,  types: ['transition','metal'] },
  { atomicNumber: 75, symbol: 'Re', name: 'Rhenium',       nameZh: '铼',      period: 6, group: 7,  atomicMass: 186.21,  types: ['transition','metal'] },
  { atomicNumber: 76, symbol: 'Os', name: 'Osmium',        nameZh: '锇',      period: 6, group: 8,  atomicMass: 190.23,  types: ['transition','metal'] },
  { atomicNumber: 77, symbol: 'Ir', name: 'Iridium',       nameZh: '铱',      period: 6, group: 9,  atomicMass: 192.22,  types: ['transition','metal'] },
  { atomicNumber: 78, symbol: 'Pt', name: 'Platinum',      nameZh: '铂',      period: 6, group: 10, atomicMass: 195.08,  types: ['transition','metal'] },
  { atomicNumber: 79, symbol: 'Au', name: 'Gold',          nameZh: '金',      period: 6, group: 11, atomicMass: 196.97,  types: ['transition','metal'] },
  { atomicNumber: 80, symbol: 'Hg', name: 'Mercury',       nameZh: '汞',      period: 6, group: 12, atomicMass: 200.59,  types: ['transition','metal','radioactive'] },
  { atomicNumber: 81, symbol: 'Tl', name: 'Thallium',      nameZh: '铊',      period: 6, group: 13, atomicMass: 204.38,  types: ['post-transition','metal','radioactive'] },
  { atomicNumber: 82, symbol: 'Pb', name: 'Lead',          nameZh: '铅',      period: 6, group: 14, atomicMass: 207.2,   types: ['post-transition','metal','radioactive'] },
  { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth',       nameZh: '铋',      period: 6, group: 15, atomicMass: 208.98,  types: ['post-transition','metal'] },
  { atomicNumber: 84, symbol: 'Po', name: 'Polonium',      nameZh: '钋',      period: 6, group: 16, atomicMass: 209,     types: ['post-transition','metal','radioactive'] },
  { atomicNumber: 85, symbol: 'At', name: 'Astatine',      nameZh: '砹',      period: 6, group: 17, atomicMass: 210,     types: ['halogen','metalloid','radioactive'] },
  { atomicNumber: 86, symbol: 'Rn', name: 'Radon',         nameZh: '氡',      period: 6, group: 18, atomicMass: 222,     types: ['noble-gas','nonmetal','radioactive'] },

  { atomicNumber: 87, symbol: 'Fr', name: 'Francium',      nameZh: '钫',      period: 7, group: 1,  atomicMass: 223,     types: ['alkali-metal','metal','radioactive'] },
  { atomicNumber: 88, symbol: 'Ra', name: 'Radium',        nameZh: '镭',      period: 7, group: 2,  atomicMass: 226,     types: ['alkaline-earth','metal','radioactive'] },

  // Actinides: Ac 放在主表 (group 3), 90-103 放在 f-block
  { atomicNumber: 89, symbol: 'Ac', name: 'Actinium',      nameZh: '锕',      period: 7, group: 3,  atomicMass: 227,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 90, symbol: 'Th', name: 'Thorium',       nameZh: '钍',      period: 7, group: null, atomicMass: 232.038, types: ['actinide','metal','radioactive'] },
  { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium',  nameZh: '镤',      period: 7, group: null, atomicMass: 231.036, types: ['actinide','metal','radioactive'] },
  { atomicNumber: 92, symbol: 'U',  name: 'Uranium',       nameZh: '铀',      period: 7, group: null, atomicMass: 238.029, types: ['actinide','metal','radioactive'] },
  { atomicNumber: 93, symbol: 'Np', name: 'Neptunium',     nameZh: '镎',      period: 7, group: null, atomicMass: 237,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium',     nameZh: '钚',      period: 7, group: null, atomicMass: 244,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 95, symbol: 'Am', name: 'Americium',     nameZh: '镅',      period: 7, group: null, atomicMass: 243,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 96, symbol: 'Cm', name: 'Curium',        nameZh: '锔',      period: 7, group: null, atomicMass: 247,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium',     nameZh: '锫',      period: 7, group: null, atomicMass: 247,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 98, symbol: 'Cf', name: 'Californium',   nameZh: '锎',      period: 7, group: null, atomicMass: 251,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium',   nameZh: '锿',      period: 7, group: null, atomicMass: 252,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 100,symbol: 'Fm', name: 'Fermium',       nameZh: '镄',      period: 7, group: null, atomicMass: 257,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 101,symbol: 'Md', name: 'Mendelevium',   nameZh: '钔',      period: 7, group: null, atomicMass: 258,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 102,symbol: 'No', name: 'Nobelium',      nameZh: '锘',      period: 7, group: null, atomicMass: 259,     types: ['actinide','metal','radioactive'] },
  { atomicNumber: 103,symbol: 'Lr', name: 'Lawrencium',    nameZh: '铹',      period: 7, group: null, atomicMass: 266,     types: ['actinide','metal','radioactive'] },

  // Superheavy elements (104-118)
  { atomicNumber: 104,symbol: 'Rf', name: 'Rutherfordium', nameZh: '𬬻',     period: 7, group: 4,  atomicMass: 267, types: ['transition','metal','radioactive'] },
  { atomicNumber: 105,symbol: 'Db', name: 'Dubnium',       nameZh: '𬭊',     period: 7, group: 5,  atomicMass: 268, types: ['transition','metal','radioactive'] },
  { atomicNumber: 106,symbol: 'Sg', name: 'Seaborgium',    nameZh: '𬭳',     period: 7, group: 6,  atomicMass: 269, types: ['transition','metal','radioactive'] },
  { atomicNumber: 107,symbol: 'Bh', name: 'Bohrium',       nameZh: '𬭛',     period: 7, group: 7,  atomicMass: 270, types: ['transition','metal','radioactive'] },
  { atomicNumber: 108,symbol: 'Hs', name: 'Hassium',       nameZh: '𬭶',     period: 7, group: 8,  atomicMass: 269, types: ['transition','metal','radioactive'] },
  { atomicNumber: 109,symbol: 'Mt', name: 'Meitnerium',    nameZh: '𫟼',     period: 7, group: 9,  atomicMass: 278, types: ['transition','metal','radioactive'] },
  { atomicNumber: 110,symbol: 'Ds', name: 'Darmstadtium',  nameZh: '𫓧',     period: 7, group: 10, atomicMass: 281, types: ['transition','metal','radioactive'] },
  { atomicNumber: 111,symbol: 'Rg', name: 'Roentgenium',   nameZh: '𫓧',     period: 7, group: 11, atomicMass: 282, types: ['transition','metal','radioactive'] },
  { atomicNumber: 112,symbol: 'Cn', name: 'Copernicium',   nameZh: '𫟼',     period: 7, group: 12, atomicMass: 285, types: ['transition','metal','radioactive'] },
  { atomicNumber: 113,symbol: 'Nh', name: 'Nihonium',      nameZh: '鉨', period: 7, group: 13, atomicMass: 286, types: ['post-transition','metal','radioactive'] },
  { atomicNumber: 114,symbol: 'Fl', name: 'Flerovium',     nameZh: '𫓧', period: 7, group: 14, atomicMass: 289, types: ['post-transition','metal','radioactive'] },
  { atomicNumber: 115,symbol: 'Mc', name: 'Moscovium',     nameZh: '镆', period: 7, group: 15, atomicMass: 288, types: ['post-transition','metal','radioactive'] },
  { atomicNumber: 116,symbol: 'Lv', name: 'Livermorium',   nameZh: '鉝', period: 7, group: 16, atomicMass: 293, types: ['post-transition','metal','radioactive'] },
  { atomicNumber: 117,symbol: 'Ts', name: 'Tennessine',    nameZh: '𬭶', period: 7, group: 17, atomicMass: 294, types: ['halogen','metalloid','radioactive'] },
  { atomicNumber: 118,symbol: 'Og', name: 'Oganesson',     nameZh: '鿏', period: 7, group: 18, atomicMass: 294, types: ['noble-gas','nonmetal','radioactive'] }
];
